# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer\AddinsWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddinsWindow(object):
    def setupUi(self, AddinsWindow):
        AddinsWindow.setObjectName("AddinsWindow")
        AddinsWindow.resize(400, 300)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/application-plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AddinsWindow.setWindowIcon(icon)
        self.addinsList = QtWidgets.QListWidget(AddinsWindow)
        self.addinsList.setGeometry(QtCore.QRect(10, 10, 381, 241))
        self.addinsList.setObjectName("addinsList")
        self.addButton = QtWidgets.QPushButton(AddinsWindow)
        self.addButton.setGeometry(QtCore.QRect(10, 260, 93, 28))
        self.addButton.setObjectName("addButton")
        self.okButton = QtWidgets.QPushButton(AddinsWindow)
        self.okButton.setGeometry(QtCore.QRect(290, 260, 93, 28))
        self.okButton.setObjectName("okButton")
        self.deleteButton = QtWidgets.QPushButton(AddinsWindow)
        self.deleteButton.setGeometry(QtCore.QRect(110, 260, 93, 28))
        self.deleteButton.setObjectName("deleteButton")

        self.retranslateUi(AddinsWindow)
        QtCore.QMetaObject.connectSlotsByName(AddinsWindow)

    def retranslateUi(self, AddinsWindow):
        _translate = QtCore.QCoreApplication.translate
        AddinsWindow.setWindowTitle(_translate("AddinsWindow", "Add-ins"))
        self.addButton.setText(_translate("AddinsWindow", "Add"))
        self.okButton.setText(_translate("AddinsWindow", "Done"))
        self.deleteButton.setText(_translate("AddinsWindow", "Delete"))
import resources_rc
